version: "3.9"

services:
  test_db:
    container_name: ${TEST_CONTRAINER_DB_NAME}
    image: postgres:latest
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_DATABASE}
    ports:
      - "${TEST_DB_PORT}:${TEST_DB_PORT}"
    networks:
      - test_database
    restart: unless-stopped

networks:
  test_database:
    driver: bridge